services:
  nginx_site1:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    networks:
      - nginx_network
    env_file:
      - .env
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
networks:
  nginx_network:
    name: ${NGINX_NETWORK_NAME}
    external: true